name: TDT4160
admins:
- djupdal
- jahre
- anderskg
tutors: []
groups_student_choice: false
accessible: false
registration: true
registration_password: null
registration_ac: null
task_dispenser: toc
dispenser_data:
    config:
        P1:
            accessibility: true
            no_stored_submissions: 5
            weight: 1.0
        P2:
            accessibility: true
            no_stored_submissions: 5
            weight: 1.0
        P3:
            accessibility: true
            no_stored_submissions: 5
            weight: 1.0
        P4:
            accessibility: true
            no_stored_submissions: 5
        T1:
            accessibility: true
            evaluation_mode: best
            no_stored_submissions: 5
            submission_limit:
                amount: -1
                period: -1
            weight: 1.0
        T2:
            accessibility: true
            evaluation_mode: best
            no_stored_submissions: 5
            submission_limit:
                amount: -1
                period: -1
            weight: 1.0
        test:
            accessibility: false
    imported: false
    toc:
    -   config:
            closed: false
        id: tasks-list
        rank: 0
        tasks_list:
            P1: 1
            P2: 2
            P3: 4
            P4: 5
            T1: 0
            T2: 3
            test: 6
        title: List of exercises
description: |-
    Dette er Ã¸vingsopplegget til TDT4160 Datamaskiner.  Du finner mer informasjon i fagets `kompendium`_.

    .. _kompendium: https://tdt4160.idi.ntnu.no/course/TDT4160/$common/TDT4160-kompendium.pdf
allow_unregister: true
allow_preview: false
registration_ac_accept: true
registration_ac_list: []
is_lti: false
lti_url: ''
lti_keys: {}
lti_send_back_grade: false
