author: Fagstaben
name: Praktisk øving 2
context: |-
    Skriv et assemblerprogram for RISC-V.

    Ved oppstart inneholder register a0 et positivt heltall – heretter kalt A – som er større enn 1. Programmet ditt skal gjøre to ting:

        1. Finn den største divisoren/faktoren som er mindre enn A.  Skriv denne til a0.
        2. Sjekk om tallet A er et kvadrattall . Skriv 1 til a1 hvis A er et kvadrat-tall, eller 0 hvis det ikke er det
problems:
    thecode:
        type: file
        allowed_exts:
        - .s
        - .S
        max_size: 1048576
        name: Last opp kildefil
        header: Last opp din kildefil her
limits:
    time: 10
    memory: 100
environment: ripes
