author: Fagstaben
name: Praktisk øving 1
context: |-
    Skriv et assemblerprogram for RISC-V som bruker registre a0-a5 som inndata.

    Disse seks registrene kan deles opp i de tre parene a0a1, a2a3, a4a5. Finn summen av hvert par og legg den største summen av disse i a0.
problems:
    thecode:
        type: file
        allowed_exts:
        - .s
        - .S
        max_size: 1048576
        name: Last opp kildefil
        header: Last opp din kildefil her
limits:
    time: 10
    memory: 100
environment: ripes
