author: Fagstaben
contact_url: ''
context: |-
    Dette er teoriøving 1.

    Her skal du svare på 8 oppgaver. Alle oppgavene blir rettet automatisk, og du må ha riktig på alle for å få godkjent øvingen.

    Som nevnt i oppgavene under skal du svare med desimaltall, heltall, og - i en oppgave - en streng.
    Alle desimaltall skal bare ha en desimal, rundes ned, og bruke en dot (ikke komma) - feks: 3.1.
    Heltall skal også rundes ned.

    Det er ingen grense på hvor mange ganger du kan levere, men bare de siste 5 lagres på INGInious.
environment_id: default
environment_parameters:
    limits:
        time: '30'
        hard_time: ''
        memory: '100'
    run_cmd: ''
environment_type: docker
file: ''
input_random: 8
name: Teoretisk øving 1
network_grading: false
problems:
    demo:
        type: code_single_line
        name: Raskere
        header: |
            .. raw:: html

              Datamaskin A bruker
              <script>
              document.write(Math.floor(input["@random"][0]* 100));
              </script>
              sekunder.  Datamaskin B bruker
              <script>
              document.write(Math.floor(input["@random"][0]* 100) + Math.floor(input["@random"][1]* 100));
              </script>
              sekunder.  Hvor mye raskere er datamaskin A i antall sekunder? Svar med et heltall.
        default: ''
    cpi:
        type: code_single_line
        name: Beregning av CPI
        header: |
            .. raw:: html

              En datamaskin bruker
              <script>
              document.write(50+Math.floor(input["@random"][0]*50));
              </script>
              klokkesykler på et program bestående av
              <script>
              document.write(Math.floor((50+Math.floor(input["@random"][0]* 50)) / (1 + input["@random"][1])));
              </script>
              instruksjoner. Hvilken CPI oppnår programmet på denne datamaskinen? Svar med et desimaltall med en desimal, og rund ned (eks: 3.1415 = 3.1).
        default: ''
    performance:
        type: code_single_line
        name: Ytelse
        header: |-
            .. raw:: html

              Alice og Bob kjører det nøyaktig samme programmet på på hver sin datamaskin. Alice blir ferdig med å kjøre programmet på 1 minutt og
              <script>
              document.write(Math.floor(input["@random"][2]*60));
              </script>
               sekunder. Bob blir først ferdig med å kjøre sitt etter 3 minutter og
              <script>
              document.write(Math.floor(input["@random"][3]*60));
              </script>
               sekunder. Hvor mye raskere er datamaskinen til Alice sammenliknet med datamaskinen til Bob? Svar med et desimaltall med en desimal, og rund ned (eks: 3.1415 = 3.1).
        default: ''
    speedup:
        type: code_single_line
        name: Speedup
        header: |-
            .. raw:: html

              Alice skal kjøpe seg en ny datamaskin. Hun finner en som reklamerer med å være dobbelt så rask som den datamaskinen hun har nå. Alice kjører ofte et program som bruker nøyaktig
              <script>
              document.write(15+Math.floor(input["@random"][4] * 45));
              </script>
               sekunder på hennes gamle datamaskin. Hvor lang tid kan hun forvente at det vil ta å kjøre dette programmet på den nye datamaskinen? Svar som et heltall eller desimaltall med en desimal (og rund ned for desimaltallet) (eks: 3.1415 = 3.1).
        default: ''
    klokkefrekvens:
        type: code_single_line
        name: Klokkefrekvens
        header: |-
            .. raw:: html

              Intel sin nye processor har en klokkefrekvens på
              <script>
              document.write(Math.floor(10 * (2+input["@random"][5]))/10);
              </script>
               GHz. Hvor mange *picosekunder* varer en klokkesykel? Svar med et heltall, og rund ned.
        default: ''
    time:
        type: code_single_line
        name: Ny tidsbruk
        header: |-
            .. raw:: html

              Vi har en gammel datamaskin med klokkefrekvens på
              <script>
              document.write(Math.floor((1+input["@random"][6]) * 10 )/10);
              </script>
               GHz som bruker nøyaktig 5 minutter på kjøre et gitt programm. Et par år senere har vi en ny datamaskin med en klokkefrekvens på 3 GHz. I tillegg har den nye datamaskinen forbedret mikroarkitekturen slik at antallet klokkesykler er 20% lavere enn på den gamle maskinen. Hvor mange sekunder kan vi forvente at programmet bruker på den nye maskinen? Rund ned til et heltall.
        default: ''
    fastest:
        type: code
        name: Alice vs Bob
        header: |-
            Alice og Bob vil finne ut hvem av dem som har den raskeste datamaskinen for et gitt program. Alice sin datamaskin har en klokkehastighet på 2.0 GHz og en CPI på 2.0 for programmet. Bob sin maskin bruker 400 picosekunder på en klokkesykel, og har en IPC på 0.8 for det samme programmet. Bruk kodeboksen under til å svare på det følgende:

            #. **Linje 1:** Hvem har den raskeste maskinen? (Svar med et navn)
            #. **Linje 2:** Hvor mye raskere er denne maskinen i forhold til den andre? (Svar med et desimaltall med en desimal, og rund ned (eks: 3.1415 = 3.1))
        language: ''
        default: |-
            <Svar på 1, Navn>
            <Svar på 2, desimaltall med en desimal, rund ned>
    averagecpi:
        type: code_single_line
        name: Gjennomsnittlig CPI
        header: |-
            .. raw:: html

              En datamaskin kjører et program med et gitt antall instruksjoner. 60% av instruksjonene tar bare 1 sykel, 20% tar
              <script>
              document.write(Math.floor(3+(input["@random"][7] * 2)));
              </script>
               sykler, 15% tar 5 sykler, mens 5% er minneinstruksjoner som tar hele 100 sykler. Hva er CPIen til datamaskinen for dette programmet? Svar med et desimaltall med en desimal, og rund ned (eks: 3.1415 = 3.1).
        default: ''
