accessible: false
name: TDT4160-25
task_dispenser: toc
dispenser_data:
    config:
        T1: {}
        T2: {}
        T3: {}
        T4: {}
    imported: false
    toc:
    -   config:
            closed: false
            hidden_if_empty: false
        tasks_list:
        - T1
        - T2
        - T3
        - T4
        - T5
        title: Exercises
