author: Fagstaben
name: Praktisk øving 4
context: |-
    Skriv et assemblerprogram for RISC-V.

    Her er du nødt til å benytte deg av en påbegynt kildefil som du finner `her`_.  Dette er nødvendig fordi denne vil skrive riktige startverdier til minnet før din egen kode kjører.

    Ved oppstart vil register a0 inneholde et frø som brukes av den utgitte kildefilen til å lage N = a1 tilfeldige tall. N > 1. Disse legges ved siden av hverandre i minnet.

    Din oppgave er å fylle ut funksjonen *find_max* slik at denne finner det største av tallene og skrive det til a0.

    .. _her: https://tdt4160.idi.ntnu.no/course/TDT4160/P4/P4_skjelett.s
problems:
    thecode:
        type: file
        allowed_exts:
        - .s
        - .S
        max_size: 1048576
        name: Last opp kildefil
        header: Last opp din kildefil her
limits:
    time: 10
    memory: 100
environment: ripes
