author: ''
contact_url: ''
context: ''
environment_id: mcq
environment_parameters: {}
environment_type: mcq
file: ''
input_random: 0
name: Teoretisk Øving 5
network_grading: false
problems:
    aksesstid:
        type: multifill
        name: Aksesstid
        header: I denne oppgaven skal du regne på forholdet mellom gjennomsnittlig
            bom-prosent og aksesstid i et cache-hierarki.
        subtask_string: ''
        subtasks:
        -   text: |-
                Gitt følgende opplysninger:
                 - Aksesstid i L1 er 2ns
                 - Gjennomsnittlig bomprosent i L1 er 10%
                 - Aksesstid i L2 er 30ns
                 - Man bommer aldri i L2

                Hva er gjennomsnittlig aksesstid? :input:`r,answer=5`
        -   text: |-
                Gitt følgende opplysninger:
                 - Aksesstid i L1 er 4ns
                 - Gjennomsnittlig bomprosent i L1 er 20%
                 - Aksesstid i L2 er 24ns
                 - Gjennomsnittlig bomprosent i L2 er 10%
                 - Aksesstid til hovedminnet er 310ns

                Hva er gjennomsnittlig aksesstid? :input:`r,answer=15`
        -   text: |-
                Gitt følgende opplysninger:
                 - Aksesstid i L1 er 3ns
                 - Gjennomsnittlig bomprosent i L1 er 30%
                 - Aksesstid i L2 er 40ns
                 - Aksesstid til hovedminnet er 500ns

                Dersom du ønsker en gjennomsnittlig akksesstid som er mindre enn 28ns, hva må gjennomsnittlig bomprosent i L2 være?
                Rund ned til nærmeste heltall: :input:`r,answer=x` %
    test:
        type: multifill
        name: Hurtigbuffer-beregninger
        header: |-
            I denne oppgaven skal du regne på forholdet mellom cache-størrelse, assosiativitet, cache-blokk-størrelse, og antall bits som brukes som tag, indeks og offset.

            Du kan få bruk for figuren som viser hvordan man deler opp adresser, fra side 421 i lærboka.

            .. image:: T5/address-bits.png
              :width: 700
              :alt: De tre delene man deler addresser i, for cache-lookup-formål.
        subtask_string: ''
        subtasks:
        -   text: |-
                Gitt følgende opplysninger om et system
                 - 32-bits addresser
                 - 4-veis set-assosiativ cache
                 - 64-bytes cache-blokker
                 - cachen inneholder totalt 2 MiB med cache-blokker

                Hvor mange bits brukes til tag? :input:`r`

                Hvor mange bits brukes til indeks? :input:`r`

                Hvor mange bits brukes til offset? :input:`r`
        -   text: |
                Gitt følgende opplysninger om et system
                 - 64-bits addresser
                 - 40-bit tag
                 - direkte-mappet cache
                 - 5-bit offset

                Hvor mange bits brukes til indeks? :input:`r`

                Hvor stor er hver cache-blokk? :input:`r`

                Hvor mange cache-blokker inneholder cachen? :input:`r`
        -   text: |-
                Gitt følgende opplysninger om et system
                 - 32-bits addresser
                 - 8-veis set assosiativ cache
                 - 1024 set
                 - 64-byte cache blokker

                Hvor mange bits brukes til tag? :input:`r`

                Hvor mange bits brukes til indeks? :input:`r`

                Hvor mange bits brukes til offset? :input:`r`

                Hvor mange KiB med cache-blokker kan cachen holde? :input:`r`

                Hvor mange KiB med lagring må brukes for å lagre alle tag-ene i cachen? :input:`r`
