author: Fagstaben
contact_url: ''
context: |-
    I denne øvingen skal vi bytte over til en pipelined 5-stegs "RISC-V"-prosessor som *mangler* noen viktige komponenter. Før du begynner, sjekk at Ripes sin valgte prosessor er **5-stage processor w/o forwarding or hazard detection**.

    De neste spørsmålene kommer til å basere seg på to filer: `A.s`_ og `B.s`_. Trykk på disse for å laste dem ned.

      .. _A.S: T2/A.s
      .. _B.S: T2/B.s
environment_id: default
environment_parameters:
    limits:
        time: '30'
        hard_time: ''
        memory: '100'
    run_cmd: ''
environment_type: docker
file: ''
input_random: 0
name: Teoretisk øving 2
network_grading: false
problems:
    no_hazard_logic:
        type: match
        name: 'A: Utregning'
        header: |-
            Se på koden i `A.s`_. Hva *bør* verdien av **a0** være etter at programmet er ferdig? Svar med et heltall på desimalform.

              .. _A.s: T2/A.s
        answer: '5'
    no_hazard_run:
        type: match
        name: 'A: Kjør'
        header: |-
            Last eller lim inn koden fra `A.s`_ inn i Ripes. Dobbelsjekk at du har satt prosessortypen til **5-stage processor w/o forwarding or hazard detection**. Kjør programmet. Hva *blir* verdien av **a0** være etter at programmet er ferdig? Svar med et heltall på desimalform.

              .. _A.s: T2/A.s
        answer: '5'
    hazard_check:
        type: match
        name: 'B: Utregning'
        header: |-
            Se på koden i `B.s`_. Hva *bør* verdien av **a0** være etter at programmet er ferdig? Svar med et heltall på desimalform.

              .. _B.s: T2/B.s
        answer: '10'
    hazard_run:
        type: match
        name: 'B: Kjør'
        header: |-
            Last eller lim inn koden fra `B.s`_ inn i Ripes. Dobbelsjekk at du har satt prosessortypen til **5-stage processor w/o forwarding or hazard detection**. Kjør programmet. Hva *blir* verdien av **a0** være etter at programmet er ferdig? Svar med et heltall på desimalform.

              .. _B.s: T2/B.s
        answer: '55'
    reflection:
        type: code
        name: Refleksjon
        header: |-
            Hvis du har gjort alt riktig merket du kanskje at det skjedde noe rart i B.
            Skriv et par linjer hvor du reflekterer rundt:

            - *Hva* som skjedde.
            - *Hvorfor* det skjedde.
            - *Hvordan* du kunne fikset det ved å endre på programmet uten å bytte prosessortype.
        language: ''
        default: ''
