author: Fagstaben
name: Praktisk øving 3
context: |-
    Skriv et assemblerprogram for RISC-V.

    Ved oppstart inneholder registrene a0-a5 6 tall. Sorter disse og legg de tilbake i a0-a5 i stigende rekkefølge (a0 skal inneholde det minste, a1 det nest minste, ..., a5 det største).

    Hvis du ønsker litt starthjelp kan du finne en påbegynt kildefil `her`_ markert med TODO der du skal fylle inn din egen kode.

    .. _her: https://tdt4160.idi.ntnu.no/course/TDT4160/P3/P3_skjelett.s
problems:
    thecode:
        type: file
        allowed_exts:
        - .s
        - .S
        max_size: 1048576
        name: Last opp kildefil
        header: Last opp din kildefil her
limits:
    time: 10
    memory: 100
environment: ripes
